Feature list Completion
RNtaate/To-Do-List pull request #1
Opened 2021-01-08 10:58 UTC by RNtaate

## What does this PR do?
- [X] Yeah coming soon..!

2021-01-08 16:54 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
You have done an amazing job in this project. Your app is deployed online, OOP, Module patterns have been used, there is clear separation of concerns between the DOM and business logic.
Let's however, fix one thing before merging.
- [ ] remove all comments from your code base


### Martin Afani

2021-01-08 16:54 UTC, whiz25 commented on src/forms.js
> +  // }
- remove this comment and any other comments in the code base

2021-01-10 12:29 UTC, RNtaate commented
## Changes made
- [X] Removed all unwanted comments in the codebase.

2021-01-10 13:03 UTC, sumancrest0001 approved these changes
### Status: Approved :100: :1st_place_medal:

**Congratulations @RNtaate and @Rumbie-Mudzie7** 

Your project is approved as you made the change suggested by the previous TSE. Now, you can merge to the master and move ahead.

**All the best with the next project.
Happy coding !!!**

2021-01-11 12:22 UTC, merged